version: "3.1"

services:
  nginx:
    build: ./nginx
    container_name: "wordpress_nginx"
    ports:
      - 80:80
    volumes:
      - ./wordpress:/var/www/html
    links:
      - php
    depends_on:
      - php
      - mysql
    restart: always

  php:
    build: ./php
    container_name: "wordpress_php"
    volumes:
      - ./wordpress:/var/www/html
    links:
      - mysql
    depends_on:
      - mysql
    restart: always

  mysql:
    build: ./mysql
    container_name: "wordpress_mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "abcd1234"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "abcd1234"
    restart: always
